import type { CardTheme, CardThemeKey } from "@/lib/card/types";

export const cardThemes: CardTheme[] = [
  {
    key: "green",
    name: "森林綠",
    primary: "#1f7a62",
    secondary: "#dff4ed",
    background: "#edf7f3",
    surface: "#ffffff",
    text: "#13332a",
    buttonText: "#ffffff",
    mutedText: "#56766c",
    border: "#cde6dc",
  },
  {
    key: "blue",
    name: "專業藍",
    primary: "#2157b6",
    secondary: "#e6eefc",
    background: "#eef4ff",
    surface: "#ffffff",
    text: "#16284c",
    buttonText: "#ffffff",
    mutedText: "#5c6e97",
    border: "#d6e1fa",
  },
  {
    key: "red",
    name: "磚紅",
    primary: "#b54444",
    secondary: "#fbe8e8",
    background: "#fff4f3",
    surface: "#ffffff",
    text: "#4b2020",
    buttonText: "#ffffff",
    mutedText: "#8c5c5c",
    border: "#f2d4d4",
  },
  {
    key: "orange",
    name: "暖橘",
    primary: "#d97706",
    secondary: "#fff0d9",
    background: "#fff8ee",
    surface: "#ffffff",
    text: "#53351a",
    buttonText: "#ffffff",
    mutedText: "#8a6b4b",
    border: "#f5dfbf",
  },
  {
    key: "purple",
    name: "霧紫",
    primary: "#6f4cc3",
    secondary: "#efe8ff",
    background: "#f7f3ff",
    surface: "#ffffff",
    text: "#31214c",
    buttonText: "#ffffff",
    mutedText: "#73648f",
    border: "#e0d6f6",
  },
  {
    key: "black-gold",
    name: "黑金",
    primary: "#c79a3b",
    secondary: "#2a2620",
    background: "#181614",
    surface: "#22201c",
    text: "#f6ead2",
    buttonText: "#1a1713",
    mutedText: "#c5b28f",
    border: "#4a4031",
  },
  {
    key: "pink",
    name: "柔粉",
    primary: "#d14f7a",
    secondary: "#ffe6ee",
    background: "#fff5f8",
    surface: "#ffffff",
    text: "#4d2332",
    buttonText: "#ffffff",
    mutedText: "#8f6170",
    border: "#f5d6e0",
  },
  {
    key: "beige",
    name: "米杏",
    primary: "#8b6a3f",
    secondary: "#f3eadc",
    background: "#f7f2ea",
    surface: "#fffdf9",
    text: "#3e3125",
    buttonText: "#ffffff",
    mutedText: "#7c6b59",
    border: "#e7dccd",
  },
];

export const cardThemeMap: Record<CardThemeKey, CardTheme> = Object.fromEntries(
  cardThemes.map((theme) => [theme.key, theme]),
) as Record<CardThemeKey, CardTheme>;
